### ISSUE TITLE
Лифт в секретной комнате не работает нормально

### ISSUE THREAD

**Issue by Kristina2005** [gamazgenii/GENS#10]
Вань, скажи мне пожалуйста, зачем ты у кнопки вызова лифта сделал такой мелкий хитбокс? ей же пользоваться нереально.

**Comment by Hraniiteli-Gamaza** [comment]
Армия собирается - Ваня обсирается

**Comment by Hraniiteli-Gamaza** [comment]
Ваня зачем ты сделал у кнопки вызова лифта хитбокс с размером твоего можно, то есть очень маленький, удали лучше свою поделку, никому она не нужна

**Comment by Kristina2005** [comment]
> Да. Этот баг существует

Это не баг, это твоя рукожопость,
В нормальных играх хитбоксы сделаны нормально а не через жопу

**Comment by Kristina2005** [comment]
> Да. Этот баг существует

И покрывают они там всю модель или нормальную зону, а не хуёвинку размером с твой мозг

**Comment by gamazgenii** [comment]
Просьба не матерится.

ps: У МЕНЯ И ТАК КОВИД

**Comment by Kristina2005** [comment]
> Просьба не матерится.
> 
> ps: У МЕНЯ И ТАК КОВИД

Ваня причём тут ковид? Мы сейчас обсуждаем твою хуйню на констракте, которая даже не работает нормально.

**Comment by gamazgenii** [comment]
Соблюдайте правила сайта!!!

ps: хватит издеваться. Я ничего вам плохого не сделал. Всё я больше не пишу не по теме. За не соблюдением правил сайта будут баны

**Comment by Tamara671games** [comment]
Быстро удаляй тут всё и выключай интернет! Мало тебе было в прошлом году???!!

**Comment by gamazgenii** [comment]
2ccc9cff66248fbaafb1aedf28beae9b64cc03b4

**Comment by gamazgenii** [comment]
#2ccc9cff66248fbaafb1aedf28beae9b64cc03b4

**Comment by gamazgenii** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/5191

Пока что это нельзя исправить

**Comment by TheReddMoon** [comment]
> 
> 
> [Scirra/Construct-3-bugs#5191](https://github.com/Scirra/Construct-3-bugs/issues/5191)
> 
> Пока что это нельзя исправить

Ну и - рукожоп.

**Comment by gamazgenii** [comment]
> > [Scirra/Construct-3-bugs#5191](https://github.com/Scirra/Construct-3-bugs/issues/5191)
> > Пока что это нельзя исправить
> 
> Ну и - рукожоп.

Проблема не во мне а в самом программном обеспечении

**Comment by gamazgenii** [comment]
Но с кнопкой в будущем я что нибудь придумаю

**Comment by TheReddMoon** [comment]
> Проблема не во мне а в самом программном обеспечении
Неумение обойти ограничения программного обеспечения - твое неумение. Использование проблемного программного решения - твое решение. Отказ от перестроения решения на рабочее - только твоя иинциатива. Ты САМ сделал сломанную кнопку и говоришь что это ограничение в ЧЬЕМ-ТО программном обеспечении. Сам сломал - другие виноваты.

**Comment by gamazgenii** [comment]
> > Проблема не во мне а в самом программном обеспечении
> 
> Неумение обойти ограничения программного обеспечения - твое неумение. Использование проблемного программного решения - твое решение. Отказ от перестроения решения на рабочее - только твоя иинциатива. Ты САМ сделал сломанную кнопку и говоришь что это ограничение в ЧЬЕМ-ТО программном обеспечении. Сам сломал - другие виноваты.

К сожалению ограничение хоть и можно обойти но это будет не кнопка потому что 3D кнопки сделать в настоящее время нельзя. Прочитай ответ из https://github.com/Scirra/Construct-3-bugs/issues/5191

Единственное что можно сделать это сделать так чтобы при приближение игрока к кнопу можно было бы нажата на клавишу на клавиатуре но не мышкой. Я подумаю как это сделать

**Comment by gamazgenii** [comment]
Если у тебя есть другие варианты то предлагай. Мне нечего больше сказать

**Comment by TheReddMoon** [comment]
Сделай возле входа триггер-зону. И кнопок никаких не надо - ни на мыше, ни на клавиатуре.

**Comment by gamazgenii** [comment]
> Сделай возле входа триггер-зону. И кнопок никаких не надо - ни на мыше, ни на клавиатуре.

Так не интересно даже

**Comment by gamazgenii** [comment]
Проблема решена.

Предлагаю это проверить в течении часа https://preview.construct.net/#xf28q2i7
