### ISSUE TITLE
Истинная концовка GENS (спойлеры)

### ISSUE THREAD

**Issue by Hraniiteli-Gamaza** [gamazgenii/GENS#14]
![IMG_20211103_214741](https://user-images.githubusercontent.com/93665046/140164885-5252484b-9679-435a-b413-dc151eab158b.jpg)

**Comment by gamazgenii** [comment]
Это не относится проблемам. Пожалуйста соблюдайте правила сайта

**Comment by Hraniiteli-Gamaza** [comment]
> Это не относится к проблемам. Пожалуйста соблюдайте правила сайта

Да пошел ты нахер черт, подчиняйся нам или тебе пиzдец, как и твоей маме
