### ISSUE TITLE
Действительно настоящая концовка GENS

### ISSUE THREAD

**Issue by Kristina2005** [gamazgenii/GENS#15]
![Безымянный](https://user-images.githubusercontent.com/93669765/140167367-d8ccf4d3-8e1b-4a11-bd86-d3b44c007b8b.png)

**Comment by gamazgenii** [comment]
Это не относится к проблемам. Пожалуйста соблюдайте правила сайта

**Comment by Kristina2005** [comment]
> Это не относится к проблемам. Пожалуйста соблюдайте правила сайта

Вань, тебе это не поможет
