### ISSUE TITLE
Тебя это не спасет, мы будем каждый день писать тебе и оставлять жалобы 

### ISSUE THREAD

**Issue by Hraniiteli-Gamaza** [gamazgenii/GENS#18]
del

**Comment by Kristina2005** [comment]
![Безымянный](https://user-images.githubusercontent.com/93669765/140174131-fa41db3d-f6e1-43b8-af21-54e69972ef79.png)

**Comment by gamazgenii** [comment]
Это не относится к проблемам. Пожалуйста соблюдайте правила сайта
