### ISSUE TITLE
Игровое поле не ограничено

### ISSUE THREAD

**Issue by TheReddMoon** [gamazgenii/GENS#37]
Так как игровое поле не ограничено, мой персонаж вышел за его пределы и сломал скрипт игры.
Теперь у меня в бесконечном цикле происходит это.
![bug](https://user-images.githubusercontent.com/93703335/140517513-a3e3502d-c992-4594-a4d4-62ed91e408cf.png)

**Comment by gamazgenii** [comment]
Будьте осторожны с этим. Я временно удалил демку. Рекомендую дождаться завтра чтобы поиграть нормально в сюжет

Если вы хотите поиграть до конца рекомендую не бегать далеко от камеры

**Comment by gamazgenii** [comment]
Если вы упали за пределами карты просто перезапустите игру

**Comment by gamazgenii** [comment]
@TheReddMoon спасибо за оставленную проблему. Ваша проблема решена. Этот баг был исправлен

**Comment by gamazgenii** [comment]
@TheReddMoon Уважаемый пользователь если вы всё ещё ждёте демо то рекомендуется иметь намного больше. Это связано с найденными проблемами которые решить быстро не получится. Выпуск новой версии демо состоится уже совсем скоро. просим вам иметь терпение и спасибо за понимания
