### ISSUE TITLE
"Скриншоты сделаны, заявление написано"

### ISSUE THREAD

**Issue by TheReddMoon** [gamazgenii/GENS#38]
Ваня, фотку заявления нам кинь, а то мы что-то не уверовали. И что там про скриншоты сообщений из группы, Князь интересуется.

**Comment by gamazgenii** [comment]
Это не относится к проблемам. Пожалуйста соблюдайте правила сайта

**Comment by TheReddMoon** [comment]
Это относится к твоим личным проблемам.

**Comment by gamazgenii** [comment]
Пожалуйста. Не пишите не по теме. Иначе будет бан
