### ISSUE TITLE
Ты побеждаешь, сынок?

### ISSUE THREAD

**Issue by TheReddMoon** [gamazgenii/GENS#39]
Ну че ты, Проказник - где игры, где контент? Так и помрешь непризнанным гением. Мы уже наснимали прохождений Генса, ищи на Ютубе, ждем новых билдов, играть не в чего: Батла - говно, ГТА тоже соснула. Одна надежда на тебя, косатик. Возрождай геймдев - рожай уже КиберГенс 2077 или че там у тебя.

**Comment by gamazgenii** [comment]
Это не относится к проблемам. Пожалуйста соблюдайте правила сайта

ps: У сейчас дела есть. Центр, Прогулки. К тому же лицензия закончилась и пока что в ближащие месяцы мало что изменится в этом проекте

**Comment by gamazgenii** [comment]
#Мы уже наснимали прохождений Генса, ищи на Ютубе

ps 2: Нету там ничего врунишка
