### ISSUE TITLE
Привет от Хранителей 

### ISSUE THREAD

**Issue by Hraniiteli-Gamaza** [gamazgenii/GENS#6]
Привет, дебил, не ждал нас, мы будем каждый день dоeбывать тебя и кидать жалобы. Скоро твой аккаунт забанят. Если ты не будешь с нами сотрудничать жалобы будут продолжать слать и все твои аккаунты будут банится
![Screenshot_2021-10-31-23-48-11-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/93665046/140083729-9e05882d-9ddf-4ab3-a5ff-210eded7af80.jpg)

**Comment by gamazgenii** [comment]
Это не относится к проблемам. Пожалуйста соблюдайте правила сайта
